version: '3'
services:
  match_web:
    build: .
    volumes:
      - ./web:/var/www/html/match
      - dbsocket:/var/run/mysqld
    ports:
      - 8081:8081
      - 3000:3000
  match_database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=matchdb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - DB_SOCKET=/var/run/mysqld/mysqld.sock
    volumes:
      - ./database:/var/lib/mysql
      - dbsocket:/var/run/mysqld
    ports:
      - 5434:5432
volumes:
  dbsocket: